services:
  app:
    build:
      context: .
    container_name: devops2
    networks:
      - lamp-network
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lamp-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3360:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamp-network

volumes:
  db_data:

networks:
  lamp-network:
    driver: bridge